# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apply_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'apply_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pply_service.proto\x12\x05\x61pply\"\x9e\x01\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\x0e\n\x06salary\x18\x05 \x01(\t\x12\x0c\n\x04type\x18\x06 \x01(\t\x12\x12\n\nexperience\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\t\x12\x12\n\neasy_apply\x18\t \x01(\x08\"Y\n\x07Profile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08headline\x18\x03 \x01(\t\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x0e\n\x06skills\x18\x05 \x03(\t\"H\n\x0c\x41pplyRequest\x12\x17\n\x03job\x18\x01 \x01(\x0b\x32\n.apply.Job\x12\x1f\n\x07profile\x18\x02 \x01(\x0b\x32\x0e.apply.Profile\"I\n\rApplyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x61pplication_id\x18\x03 \x01(\t2B\n\x0c\x41pplyService\x12\x32\n\x05\x41pply\x12\x13.apply.ApplyRequest\x1a\x14.apply.ApplyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apply_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOB']._serialized_start=31
  _globals['_JOB']._serialized_end=189
  _globals['_PROFILE']._serialized_start=191
  _globals['_PROFILE']._serialized_end=280
  _globals['_APPLYREQUEST']._serialized_start=282
  _globals['_APPLYREQUEST']._serialized_end=354
  _globals['_APPLYRESPONSE']._serialized_start=356
  _globals['_APPLYRESPONSE']._serialized_end=429
  _globals['_APPLYSERVICE']._serialized_start=431
  _globals['_APPLYSERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
